MODEL:
  META_ARCHITECTURE: "ERRSeg"
  ENC:
    CLIP_MODEL_NAME: "convnext_base_w_320"
    CLIP_PRETRAINED_WEIGHTS: "laion_aesthetic_s13b_b82k"
  CLIP_PIXEL_MEAN: [123.675, 116.280, 103.530]
  CLIP_PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "ERRSEGHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 171
    SAMPLE_CLASSES_NUM: 32
    TRAIN_CLASS_JSON: "datasets/coco.json"
    TEST_CLASS_JSON: "datasets/coco.json"
    TEXT_GUIDANCE_DIM: 640
    TEXT_GUIDANCE_PROJ_DIM: 128
    CORR_FPN_INTER_DIM: 256
    CORR_FPN_FUSION_DIM: 128
    GUIDANCE_FPN_INTER_DIM: 256
    GUIDANCE_FPN_FUSION_DIM: 128
    IMAGE_GUIDANCE_DIMS: [1024, 512, 256, 128]
    DECODER_GUIDANCE_DIMS: [512, 256, 128]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16, 8]
    DECODER_DIMS: [64, 32, 16]
    AGGREGATOR_SCALE_RATIO: [2, 2, 2, 2]
    AGGREGATOR_DIM: 128
    CLIP_FINETUNE: "weight"
SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 4
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.0002
  MAX_ITER: 80000
  CLIP_MULTIPLIER: 0.01
INPUT:
  MIN_SIZE_TRAIN: (640, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 640
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
DATASETS:
  TRAIN: ("coco_2017_train_stuff_all_sem_seg",)
  TEST: ("coco_2017_test_stuff_all_sem_seg",)
TEST:
  EVAL_PERIOD: 80000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
VERSION: 2
CUDNN_BENCHMARK: True
